# Generated by Django 6.1.1 on 2026-09-26 07:45

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('customer', 'Customer'), ('worker', 'Worker')], max_length=10)),
                ('name', models.CharField(blank=True, max_length=120)),
                ('phone', models.CharField(blank=True, max_length=20)),
                ('location', models.CharField(blank=True, max_length=80)),
                ('category', models.CharField(blank=True, max_length=40)),
                ('skills', models.CharField(blank=True, max_length=300)),
                ('experience_years', models.IntegerField(default=0)),
                ('hourly_rate', models.IntegerField(default=0)),
                ('daily_rate', models.IntegerField(default=0)),
                ('bio', models.CharField(blank=True, max_length=300)),
                ('available', models.BooleanField(default=True)),
                ('verified', models.BooleanField(default=False)),
                ('rating_avg', models.FloatField(default=0)),
                ('rating_count', models.IntegerField(default=0)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(max_length=40)),
                ('booking_type', models.CharField(choices=[('hourly', 'Hourly'), ('daily', 'Daily'), ('multi_day', 'Multi-day'), ('emergency', 'Emergency')], default='hourly', max_length=12)),
                ('hours', models.IntegerField(default=0)),
                ('days', models.IntegerField(default=0)),
                ('repeat_daily', models.BooleanField(default=False)),
                ('scheduled_at', models.DateTimeField(blank=True, null=True)),
                ('address', models.CharField(blank=True, max_length=200)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('accepted', 'Accepted'), ('rejected', 'Rejected'), ('in_progress', 'In progress'), ('completed', 'Completed'), ('cancelled', 'Cancelled')], default='pending', max_length=15)),
                ('price', models.IntegerField(default=0)),
                ('payment_method', models.CharField(default='cash', max_length=20)),
                ('checked_in_at', models.DateTimeField(blank=True, null=True)),
                ('checked_out_at', models.DateTimeField(blank=True, null=True)),
                ('rating', models.IntegerField(blank=True, null=True)),
                ('review', models.CharField(blank=True, max_length=300)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bookings_as_customer', to='core.profile')),
                ('worker', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bookings_as_worker', to='core.profile')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
